# Generated by Django 4.0.5 on 2022-06-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_rename_ticket_message_number_ticket_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="status_id",
            new_name="status",
        ),
    ]
